### ISSUE TITLE
Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function

### ISSUE THREAD

**Issue by AlokPundir** [tradingview/charting-library-examples#178] opened 2020-06-25 03:52 UTC
**Bug report**

Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function
(anonymous function)
src/charting_library/charting_library.min.js:232
229 | i.addEventListener("load", e, !1);
230 | })),
231 | this._innerWindowLoaded.then(function () {

232 | t._innerWindow().widgetReady(function () {
| ^ 233 | t._ready = !0;
234 | for (var e = 0, o = t._readyHandlers; e < o.length; e++) {
235 | var i = o[e];

**Comment by Moshnogorskaya** [comment] 2020-06-25 13:24
Duplicate of https://github.com/tradingview/charting_library/issues/5085

**Closed** 2020-06-25 13:24 UTC

**Comment by daisai3** [comment] 2021-02-01 16:55
@Moshnogorskaya , this link does not work.
https://github.com/tradingview/charting_library/issues/5085

**Comment by timocov** [comment] 2021-02-02 09:46
> this link does not work.

@daisai3 do you have an access to charting_library?

**Comment by daisai3** [comment] 2021-02-02 09:50
@timocov , yesterday I debugged the code line by line and noticed that it was an issue of version and configuration issue. I added charting_library in correct version both on `/public` folder and `/src` folders and finally I could see the charts on my side. :)

**Comment by manfulMr** [comment] 2021-07-05 03:31
这个报错该如何处理啊？

**Comment by OluAgunloye** [comment] 2021-08-24 01:18
> @timocov , yesterday I debugged the code line by line and noticed that it was an issue of version and configuration issue. I added charting_library in correct version both on `/public` folder and `/src` folders and finally I could see the charts on my side. :)

How did you get around this? What versions did you have to use ?

**Comment by manfulMr** [comment] 2021-08-24 01:26
I use TradingView version 19, which version do you use, but I made a mistake when I introduced it in the first step. I can't find the reason. Could you help me analyze the reason? thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tradingview/charting-library-examples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tradingview/charting-library-examples] Unhandled Rejection (TypeError): t._innerWindow(...).widgetReady is not a function (#178)





  
@timocov , yesterday I debugged the code line by line and noticed that it was an issue of version and configuration issue. I added charting_library in correct version both on /public folder and /src folders and finally I could see the charts on my side. :)
  
How did you get around this? What versions did you have to use ?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by devpool-company** [comment] 2022-03-23 16:24
I faced the same error: "n._innerWindow().widgetReady is not a function".
In my case it was because of Cloudflare (where I hosted the app) and it's option "Rocket Loader".
Rocket Loader feature of Cloudflare wraps content of the html file, what is loaded by TV iFrame.
The iFrame wasn't properly loaded, thus the needed functions on this iFrame were missing.

Once I disabled "Rocket Loader" in Cloudflare dashboard, I was needed just to clear browser's cache.

That's how you can tell, that's your case:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/47427658/159747612-02b9959a-1abf-47e9-8475-3f0fdedebcc9.png">
