### ISSUE TITLE
Did anyone made Nuxt.js example before?

### ISSUE THREAD

**Issue by sefaemrahoglu** [tradingview/charting-library-examples#225] opened 2021-05-06 12:20 UTC
I need nuxt.js example immediately . I tried but got an 'window is not defined' error. I did just like vue.js example

**Comment by timocov** [comment] 2021-05-06 12:51
First of all, it's a duplicate of #30. Please don't create duplicated issues, it doesn't help to solve your issue.

Secondly, please look at https://github.com/tradingview/charting-library-examples/pull/214. It didn't reviewed yet, but I think it might help you.

**Closed by timocov** 2021-05-06 12:51 UTC
