### ISSUE TITLE
ReactJs × TypeError: i.contentWindow.widgetReady is not a function

### ISSUE THREAD

**Issue by MikeHibbert** [tradingview/charting-library-examples#79] opened 2019-01-23 13:07 UTC
**To Reproduce**

1. Clone the repo
2. Go to 'react-javascript' folder
3. Copy charting_library to the 'src' folder
4. Copy datafeeds to the public folder
5. Run command 'yarn start' or 'npm start' 
6. See error 'undefined define' error
7. Add the following to the top of charting_library.min.js:
   /*global define:true*/
  /*eslint no-undef: "error"*/
  /* eslint-disable no-unused-expressions */
8.  Run command 'yarn start' or 'npm start' 
9. See error:
   TypeError: i.contentWindow.widgetReady is not a function
   HTMLIFrameElement.n
   src/charting_library/charting_library.min.js:4

My package.json is:

{
  "name": "charting-library-react-js-example",
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build"
  }
}

I also found a issue that mentioned that disabling the serviceworker would help but this example doesnt include one.

**Comment by kirchet** [comment] 2019-01-23 16:11
Duplicate of #15

**Closed by kirchet** 2019-01-23 16:11 UTC
