### ISSUE TITLE
Why is the volume of the latest version of the Library so large, nearly 20M, can it be streamlined when introduced

### ISSUE THREAD

**Issue by EduTekCompany** [tradingview/charting-library-examples#393] opened 2024-08-28 03:14 UTC
Why is the volume of the latest version of the Library so large, nearly 20M, can it be streamlined when introduced

**Comment by romfrancois** [comment] 2024-08-28 05:46
Closing as a duplicate of [8776](https://github.com/tradingview/charting_library/issues/8776)

**Closed by romfrancois** 2024-08-28 05:46 UTC
