### ISSUE TITLE
calculateHistoryDepth Example

### ISSUE THREAD

**Issue by Rishabhai** [tradingview/charting-library-examples#158] opened 2020-01-13 08:53 UTC
- **Framework/library:**  React
- **Link to page with the framework/library:**  https://reactjs.org/

I am using calculateHistoryDepth api and i am facing few issue with it.
it is working as expected for the first call to fetch Data with subsequent calls depth are random.

My Implementation :- 
i have defind a __**resolutionToIntervalMapping**_ function_ which maps different resolution to depths and have called it in this way.

calculateHistoryDepth: (resolution, resolutionBack, intervalBack) => {
    return resolutionToIntervalMapping(resolution, resolutionBack, intervalBack)
}

**_function_**
const resolutionToIntervalMapping = (resolution, resolutionBack, intervalBack) => {
  let returnValue = {
    resolutionBack,
    intervalBack
  }
  if(resolution < 5) {
    returnValue = {
      resolutionBack: 'D',
      intervalBack: 5
    }
  }
  if(resolution >= 5 && resolution < 15) {
    returnValue = {
      resolutionBack: 'D',
      intervalBack: 15
    }
  }
  return returnValue
}

I expect to call 5 days of minute data if resolution is 5 min or less but this code doesn't work as expected for subsequent calls after 1st call.
An example for this case will be great help.
Thanks.

**Comment by timocov** [comment] 2020-01-13 09:34
Duplicate of https://github.com/tradingview/charting_library/issues/4656

**Closed by timocov** 2020-01-13 09:34 UTC
