### ISSUE TITLE
NextJS - chart only shows in build and not in dev

### ISSUE THREAD

**Issue by mnkhod** [tradingview/charting-library-examples#234] opened 2021-06-22 05:02 UTC
reverting back from webpack 5 to webpack 4 fixes the problem

but this fix is shitty is there anyway to make it work in nextjs?

can there please be an example of nextjs and typescript projects :<

**Comment by timocov** [comment] 2021-06-22 08:38
Duplicate of #224

**Closed by timocov** 2021-06-22 08:38 UTC
