### ISSUE TITLE
How to Integrate on Flutter

### ISSUE THREAD

**Issue by WansZzang** [tradingview/charting-library-examples#252] opened 2021-11-02 01:27 UTC
Hi, This is Kay Kim who is developing trading chart on Flutter.

We've already integrated charting_library to our cryptocurrency exchange system. 

In this time, It is required to renewal Mobile Trading System. At last version, MTS was developed by Lua. But the new version has been developed by Flutter.

It was realized trading chart via mobile webview. The web side was developed by Vue.js. But it has few seconds for connecting and loading. Therefore we are trying to integrate HTML and JS sources to Flutter Web parser, instead of the webview.

The Flutter's webparser is able to draw UI using HTML and JS source directly.

At this point, I need your help to make HTML and JS source for the traiding chart. 

Q1. Is there any front level sample source using only HTML and JS?
Q2. Is there better way to realized on Flutter mobile app?
      : For your information, Flutter is able to integrate Android and iOS native source.

I'm looking forward to get your technically answer.

Best Regard

**Comment by coditori** [comment] 2021-11-19 18:02
I think you can implement Android and IOS separately (as native code)

**Comment by timocov** [comment] 2021-11-23 17:49
Duplicate of #81

**Closed by timocov** 2021-11-23 17:49 UTC
